language: ruby
before_install:
  - sudo add-apt-repository -y ppa:miurahr/vagrant
  - sudo apt-get update -qq
  - sudo apt-get install -qq qemu-kvm qemu
  - sudo apt-get install -qq libvirt-dev libvirt-bin
  - sudo apt-get install -qq -y bsdtar
  - gem install bundler -v '1.5.2'
rvm:
  - 2.0.0
script:
  - export rvmsudo_secure_path=1
  - export VAGRANT_FORCE_BUNDLER=1
  - rvmsudo ruby --version
  - rvmsudo gem --version
  - rvmsudo bundle --version
  - rvmsudo bundle exec rake box:add
  - rvmsudo bundle exec rake spec
  - rvmsudo bundle exec rake box:remove
